project:
  type: website
  output-dir: docs

website:
  title: "Prime Geospatial"
  search: true                  # Adds a top-right search bar just like academic sites
  navbar:
    pinned: true
    background: "#2A5A5C"            # Gives you that sharp, high-contrast header bar
    foreground: "#FFFFFF"
    left:
      # Home button removed
      - href: about.qmd
        text: About us
      - href: people.qmd
        text: Our Team
      - href: services.qmd
        text: Services
      - href: projects2.qmd  # Or "Case Studies / White Papers"
        text: Projects
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css # <-- This line tells Quarto to look for your CSS file!
    toc: true                   # Generates the right-hand page navigation menu
    toc-location: right
# Try changing 'flatly' to 'lux' or 'journal'

