project:
  type: website
  output-dir: docs

website:
  title: "Prime Geospatial"
  search: true                  # Adds a top-right search bar just like academic sites
  navbar:
    background: dark            # Gives you that sharp, high-contrast header bar
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About us
      - href: services.qmd
        text: Services
      - href: projects.qmd  # Or "Case Studies / White Papers"
        text: Projects      
      - href: projects2.qmd  # Or "Case Studies / White Papers"
        text: Projects2
      - href: projects3.qmd  # Or "Case Studies / White Papers"
        text: Projects3
      - href: people.qmd
        text: Our Team
      - href: people3.qmd
        text: Our Team3
      - href: people4.qmd
        text: Our Team4
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css # <-- This line tells Quarto to look for your CSS file!
    toc: true                   # Generates the right-hand page navigation menu
    toc-location: right

